# Generated by Django 3.0.1 on 2020-01-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('notToSay', 'Hidden')], max_length=20, verbose_name='gender')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='phone number')),
                ('email', models.CharField(max_length=45, unique=True, verbose_name='Mail address')),
                ('date_of_birth', models.DateField(verbose_name='birth date')),
                ('address', models.TextField(verbose_name='Address')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
            ],
        ),
    ]
